name: Nasa project CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: use node js version 22
        uses: action/setup-node@v2
        with:
          node-version: '22'
      - run: npm install
      - run: npm run build --prefix client
